services:
  - type: web
    name: prisma-nextjs
    env: node
    buildCommand: npm install && npx prisma generate && node scripts/fix-ui-imports.js && node scripts/prebuild.js && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false 