services:
  - type: web
    name: response-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 16.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false 